- hosts: all
  become: true
  tasks:
  - name: installing apache2 in Ubuntu web-server
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: adding php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: installing httpd in CentOS web-server
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: adding php support for httpd
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"

